# Generated by Django 5.1.1 on 2024-09-26 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customusermodel_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserModel',
        ),
    ]
