# Generated by Django 4.2.1 on 2024-09-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zip', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('cc_num', models.CharField(max_length=16)),
                ('trans_day', models.IntegerField()),
                ('trans_hour', models.IntegerField()),
                ('trans_month', models.IntegerField()),
                ('trans_year', models.IntegerField()),
                ('trans_minute', models.IntegerField()),
                ('is_fraud', models.BooleanField(default=False)),
                ('blockchain_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
