# Generated by Django 4.2.1 on 2024-09-27 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_blockchain_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blockchain',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='blockchain_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='uncategorized', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cc_num',
            field=models.CharField(default='0000000000000000', max_length=16),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trans_day',
            field=models.IntegerField(default=27),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trans_hour',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trans_minute',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trans_month',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trans_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='zip_code',
            field=models.IntegerField(default=0),
        ),
    ]
